# Generated by Django 5.2.7 on 2025-11-07 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0003_alter_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='game_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='game_started_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 17, 7, 23, 665228)),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
