# Generated by Django 5.2.7 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0004_qrcode_player_game_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_started_datetime',
            field=models.IntegerField(default=0),
        ),
    ]
