# Generated by Django 5.2.7 on 2025-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0005_alter_player_game_started_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_started_datetime',
            field=models.BigIntegerField(default=0),
        ),
    ]
